name: Publish Docker

on:
  push:
    branches:
      - main

jobs:
  publish-dockerhub:
    name: Build Redash
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseImageTag: ["8.0.2.b37747", "7.0.0.b18042"]
        include:
          - baseImageTag: "8.0.2.b37747"
            postfixVersion: "8.0.2"
          - baseImageTag: "7.0.0.b18042"
            postfixVersion: "7.0.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            doomoolmori/redash:${{ matrix.postfixVersion }}
          tag_with_ref: true
          build-args: |
            version=${{ matrix.baseImageTag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}